### ISSUE TITLE
No attachments have been sent

### ISSUE THREAD

**Issue by suchenglong** [mattermost/mattermost-bot-sample-golang#10]
hello ,I look at you sample,but it don't give  me a sample about sending attachments .can you give a sample with it,thank you!

**Comment by lindy65** [comment]
Hello @suchenglong,

Thank you for your feedback,

In response, from one of our devs, is that the bot sample does not have an example for sending attachments.  The driver supports it, there isn't a sample.

**Comment by lfbrock** [comment]
Closing this issue, if someone would like to do another example bot with sending attachments or a tutorial around creating bots let us know!
