### ISSUE TITLE
Direct Messages?

### ISSUE THREAD

**Issue by dustinupdyke** [mattermost/mattermost-bot-sample-golang#13]
Is it possible to call the client and retrieve a list of direct message options? I can get channels via:

```
x, y := client.SearchChannels(oteam.Id, search)
fmt.Println(y)
for _, t := range x {
   println(t.Name + "  :  " + t.Id)
}
```

But this does not return direct message channels. I would like the bot to be able to respond to 1:1 commands as well.

Thanks.

**Comment by coreyhulen** [comment]
I think you want client.GetChannelsForTeamForUser(...) then iterate through the results and looks for channel.type = 'D'

**Comment by lindy65** [comment]
Hi @dustinupdyke 

Circling back to see whether you've resolved your issue with the help from Corey above?

**Comment by dustinupdyke** [comment]
Yes, thank you.
