### ISSUE TITLE
cant get mattermost bot to run

### ISSUE THREAD

**Issue by eyebank** [mattermost/mattermost-bot-sample-golang#17]
After following the relevant instructions,

git clone https://github.com/mattermost/mattermost-bot-sample-golang.git

cd mattermost-bot-sample-golang

then I typed this: make run

received errors: Any suggestions?

**Comment by MusikPolice** [comment]
What specific errors did you receive?

**Comment by eyebank** [comment]
Hi,
On Make Run 
Can't find package "github.com/matttermost/mattermost-server/model"

See attached
Thank you
![golang2](https://user-images.githubusercontent.com/8021595/33251811-a3513ada-d307-11e7-91a5-e286e230bf4d.jpg)

**Comment by MusikPolice** [comment]
Looks like your development environment is structured incorrectly. Did you follow the [Developer Machine Setup](https://docs.mattermost.com/developer/dev-setup.html) guide? I would expect you to have checked out the code to somewhere like `~/go/src/github.com/mattermost/mattermost-bot-sample-golang` or `/usr/local/go/src/github.com/mattermost/mattermost-bot-sample-golang`. You'll also need to have the `mattermost-server` repository checked out to `../mattermost-server` (relative to your bot sample directory). This is all covered in the setup docs.

**Comment by eyebank** [comment]
Thanks. We are  new to go lang and this process. We can get a normal go lang test to run. So I am confident the go lang installation is correct.

Please permit another question. How would one modify this sample code to interface with a custom installation of Mattermost on Ubuntu with the mattermost instance residing in /home/mattermost/bin?

Thanks for helping.

**Comment by MusikPolice** [comment]
There should be no need to modify the bot in any way. It just expects your custom server to be running at `http://localhost:8065`. If your server is listening on some other ip address or port, [you can modify this url|https://github.com/mattermost/mattermost-bot-sample-golang/blob/master/bot_sample.go#L42].

**Comment by eyebank** [comment]
@MusikPolice you may close this ticket. I had missed this step: issue command "glide up". 
Thank you.
