### ISSUE TITLE
Cannot find package "github.com/mattermost/mattermost-server/model"

### ISSUE THREAD

**Issue by dazulu** [mattermost/mattermost-bot-sample-golang#19]
Getting `cannot find package "github.com/mattermost/mattermost-server/model"` during `make run`. Is the implementation just too old? 🤔

**Comment by jespino** [comment]
Hi @dazulu, do you have mattermost-server code downloaded in your `$GOPATH/src/github.com/mattermost/mattermost-server`?

**Comment by dazulu** [comment]
Ah the winding road of being a complete beginner to a language. Thank you.
