### ISSUE TITLE
Golang bog Two Factor Authentication

### ISSUE THREAD

**Issue by EbsrVlee** [mattermost/mattermost-bot-sample-golang#23]
Hello!
I have a golang bot that I am trying to run with two factor authentication enabled on mattermost.

I've added Client4.LoginWithMFA() to the golang client code but get these errors below.

undefined: Client 4
undefined: User
undefined: Response
Makefille:15: recipe for target 'run' failed
make: *** [run] Error 2

What am I missing?

Thank you again for all your help!

(https://github.com/mattermost/mattermost-server/blob/master/model/client4.go#L638)

**Comment by hanzei** [comment]
Hey @EbsrVlee,

I would like to keep the discussion about this in #22. Would you be fine with closing this?

**Comment by EbsrVlee** [comment]
Hi @hanzei , yes I would be fine in moving this discussion into #22

Thanks.
