### ISSUE TITLE
Can't build the example bot

### ISSUE THREAD

**Issue by dschulz** [mattermost/mattermost-bot-sample-golang#3]
After following the relevant instructions, 

`git clone https://github.com/mattermost/mattermost-bot-sample-golang.git`

`cd mattermost-bot-sample-golang`

then I did this

`glide up`

the build fails with

`dschulz@testserver:~/mattermost-bot-sample-golang$ make run` 
`go run   *.go`
`# command-line-arguments`
`./bot_sample.go:203: event.ChannelId undefined (type *model.WebSocketEvent has no field or method ChannelId)`
`./bot_sample.go:213: event.UserId undefined (type *model.WebSocketEvent has no field or method UserId)`
`Makefile:15: recipe for target 'run' failed`
`make: *** [run] Error 2`

What am I doing wrong?

**Comment by perigee** [comment]
From https://github.com/mattermost/platform/blob/master/model/websocket_message.go#L49, 

you should change the code to 

```
203: event.Broadcast.ChannelId
213: event.Broadcast.UserId
```

**Comment by hmhealey** [comment]
Thanks for your help solving this problem, @perigee. This has been fixed now.
