### ISSUE TITLE
Unresponsive after some time

### ISSUE THREAD

**Issue by gravufo** [mattermost/mattermost-bot-sample-golang#37]
This sample bot stops responding if left running for a while.
I found an issue [here](https://github.com/infracloudio/botkube/issues/201) which details the same behavior and it was fixed by restarting the websocket connection when an error is detected.

This logic should be added to the sample to prevent newbies from hitting the same issue.

**Comment by patatman** [comment]
This is a good point, I fixed it in my own bot. 
I'll make a PR to fix this issue in the example.
