### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by mogren** [mattermost/mattermost-bot-sample-golang#7]
What license is this sample? The headers only say:

// Copyright (c) 2016 Mattermost, Inc. All Rights Reserved.
// See License.txt for license information.

**Comment by jasonblais** [comment]
Thanks! Created PR here: https://github.com/mattermost/mattermost-bot-sample-golang/pull/8

**Comment by it33** [comment]
Merged, thanks @mogren thanks @jasonblais
